CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'maygen'@'%' IDENTIFIED BY '${WP_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON wordpress.* TO 'maygen'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '${WP_ADMIN_PASSWORD}'';
